dist: xenial
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
script:
  - pip install .[dev]
  - pre-commit run --all-files
  - coverage run --source flapison -m pytest -v
after_success:
  - coveralls
